/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Date = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AppData = IDL.Record({
  'lastUpdated' : Time,
  'version' : IDL.Nat,
  'ledgerState' : IDL.Opt(IDL.Text),
  'userProfile' : IDL.Opt(UserProfile),
});
export const CoTravellerIncome = IDL.Record({
  'date' : Date,
  'note' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoTravellerIncome' : IDL.Func([IDL.Nat, Date, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fetchAppData' : IDL.Func([], [IDL.Opt(AppData)], ['query']),
  'getAllBalances' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoTravellerIncomes' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CoTravellerIncome)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAppData' : IDL.Func([AppData], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startCharge' : IDL.Func([IDL.Text, IDL.Nat, IDL.Vec(IDL.Principal)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Date = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AppData = IDL.Record({
    'lastUpdated' : Time,
    'version' : IDL.Nat,
    'ledgerState' : IDL.Opt(IDL.Text),
    'userProfile' : IDL.Opt(UserProfile),
  });
  const CoTravellerIncome = IDL.Record({
    'date' : Date,
    'note' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoTravellerIncome' : IDL.Func(
        [IDL.Nat, Date, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fetchAppData' : IDL.Func([], [IDL.Opt(AppData)], ['query']),
    'getAllBalances' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoTravellerIncomes' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CoTravellerIncome)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAppData' : IDL.Func([AppData], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startCharge' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Principal)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };