/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TripTime = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
});
export const Date = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const CoTravellerIncome = IDL.Record({
  'tripTime' : IDL.Opt(TripTime),
  'date' : Date,
  'note' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const Category = IDL.Variant({
  'accomodation' : IDL.Null,
  'cashWithdrawal' : IDL.Null,
  'other' : IDL.Null,
  'food' : IDL.Null,
  'transport' : IDL.Null,
  'tips' : IDL.Null,
  'shopping' : IDL.Null,
  'entryFee' : IDL.Null,
  'activity' : IDL.Null,
});
export const Expense = IDL.Record({
  'tripTime' : IDL.Opt(TripTime),
  'date' : Date,
  'note' : IDL.Opt(IDL.Text),
  'category' : Category,
  'amount' : IDL.Nat,
});
export const OtherPendingAmount = IDL.Record({
  'id' : IDL.Text,
  'date' : Date,
  'traveller' : IDL.Text,
  'comment' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AppData = IDL.Record({
  'lastUpdated' : Time,
  'otherPendingAmounts' : IDL.Vec(OtherPendingAmount),
  'version' : IDL.Nat,
  'ledgerState' : IDL.Opt(IDL.Text),
  'userProfile' : IDL.Opt(UserProfile),
});
export const TabPermission = IDL.Record({
  'access' : IDL.Text,
  'tabKey' : IDL.Text,
});
export const SharedDataResult = IDL.Record({
  'permissions' : IDL.Vec(TabPermission),
  'ledgerState' : IDL.Opt(IDL.Text),
});
export const UserProfileExtended = IDL.Record({
  'sex' : IDL.Opt(IDL.Text),
  'vehicleNumber' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Opt(IDL.Text),
  'firstName' : IDL.Opt(IDL.Text),
});
export const ShareAccessEntry = IDL.Record({
  'permissions' : IDL.Vec(TabPermission),
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoTravellerIncome' : IDL.Func([CoTravellerIncome], [], []),
  'addExpense' : IDL.Func([Expense], [], []),
  'addExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
  'addOrUpdateOtherPendingAmount' : IDL.Func([OtherPendingAmount], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteOtherPendingAmount' : IDL.Func([IDL.Text], [], []),
  'fetchAppData' : IDL.Func([], [IDL.Opt(AppData)], ['query']),
  'getAdminSharedData' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SharedDataResult)],
      ['query'],
    ),
  'getAdminSharedDataByEmail' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(SharedDataResult)],
      ['query'],
    ),
  'getShareAccessVisitCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'recordSharedUserVisit' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'getAllBalances' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserProfileExtended' : IDL.Func(
      [],
      [IDL.Opt(UserProfileExtended)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoTravellerIncomes' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CoTravellerIncome)],
      ['query'],
    ),
  'getExpenses' : IDL.Func([IDL.Principal], [IDL.Vec(Expense)], ['query']),
  'getOtherPendingAmounts' : IDL.Func(
      [],
      [IDL.Vec(OtherPendingAmount)],
      ['query'],
    ),
  'getShareAccessConfig' : IDL.Func([], [IDL.Vec(ShareAccessEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerSharedUserEmail' : IDL.Func([IDL.Text], [], []),
  'saveAppData' : IDL.Func([AppData], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfileExtended' : IDL.Func([UserProfileExtended], [], []),
  'saveShareAccessConfig' : IDL.Func([IDL.Vec(ShareAccessEntry)], [], []),
  'startCharge' : IDL.Func([IDL.Text, IDL.Nat, IDL.Vec(IDL.Principal)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TripTime = IDL.Variant({ 'morning' : IDL.Null, 'evening' : IDL.Null });
  const Date = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const CoTravellerIncome = IDL.Record({
    'tripTime' : IDL.Opt(TripTime),
    'date' : Date,
    'note' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'accomodation' : IDL.Null,
    'cashWithdrawal' : IDL.Null,
    'other' : IDL.Null,
    'food' : IDL.Null,
    'transport' : IDL.Null,
    'tips' : IDL.Null,
    'shopping' : IDL.Null,
    'entryFee' : IDL.Null,
    'activity' : IDL.Null,
  });
  const Expense = IDL.Record({
    'tripTime' : IDL.Opt(TripTime),
    'date' : Date,
    'note' : IDL.Opt(IDL.Text),
    'category' : Category,
    'amount' : IDL.Nat,
  });
  const OtherPendingAmount = IDL.Record({
    'id' : IDL.Text,
    'date' : Date,
    'traveller' : IDL.Text,
    'comment' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AppData = IDL.Record({
    'lastUpdated' : Time,
    'otherPendingAmounts' : IDL.Vec(OtherPendingAmount),
    'version' : IDL.Nat,
    'ledgerState' : IDL.Opt(IDL.Text),
    'userProfile' : IDL.Opt(UserProfile),
  });
  const TabPermission = IDL.Record({
    'access' : IDL.Text,
    'tabKey' : IDL.Text,
  });
  const SharedDataResult = IDL.Record({
    'permissions' : IDL.Vec(TabPermission),
    'ledgerState' : IDL.Opt(IDL.Text),
  });
  const UserProfileExtended = IDL.Record({
    'sex' : IDL.Opt(IDL.Text),
    'vehicleNumber' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Opt(IDL.Text),
    'firstName' : IDL.Opt(IDL.Text),
  });
  const ShareAccessEntry = IDL.Record({
    'permissions' : IDL.Vec(TabPermission),
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoTravellerIncome' : IDL.Func([CoTravellerIncome], [], []),
    'addExpense' : IDL.Func([Expense], [], []),
    'addExpenses' : IDL.Func([IDL.Vec(Expense)], [], []),
    'addOrUpdateOtherPendingAmount' : IDL.Func([OtherPendingAmount], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteOtherPendingAmount' : IDL.Func([IDL.Text], [], []),
    'fetchAppData' : IDL.Func([], [IDL.Opt(AppData)], ['query']),
    'getAdminSharedData' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SharedDataResult)],
        ['query'],
      ),
    'getAdminSharedDataByEmail' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(SharedDataResult)],
        ['query'],
      ),
    'getShareAccessVisitCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'recordSharedUserVisit' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'getAllBalances' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserProfileExtended' : IDL.Func(
        [],
        [IDL.Opt(UserProfileExtended)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoTravellerIncomes' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CoTravellerIncome)],
        ['query'],
      ),
    'getExpenses' : IDL.Func([IDL.Principal], [IDL.Vec(Expense)], ['query']),
    'getOtherPendingAmounts' : IDL.Func(
        [],
        [IDL.Vec(OtherPendingAmount)],
        ['query'],
      ),
    'getShareAccessConfig' : IDL.Func(
        [],
        [IDL.Vec(ShareAccessEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerSharedUserEmail' : IDL.Func([IDL.Text], [], []),
    'saveAppData' : IDL.Func([AppData], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfileExtended' : IDL.Func([UserProfileExtended], [], []),
    'saveShareAccessConfig' : IDL.Func([IDL.Vec(ShareAccessEntry)], [], []),
    'startCharge' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Principal)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };