/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Amount = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Date = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllBalances' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Amount))],
      ['query'],
    ),
  'getBalance' : IDL.Func([IDL.Principal], [Amount], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func([Date, Amount, IDL.Opt(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startCharge' : IDL.Func([IDL.Text, Amount, IDL.Vec(IDL.Principal)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Amount = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Date = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllBalances' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Amount))],
        ['query'],
      ),
    'getBalance' : IDL.Func([IDL.Principal], [Amount], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func([Date, Amount, IDL.Opt(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startCharge' : IDL.Func(
        [IDL.Text, Amount, IDL.Vec(IDL.Principal)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };