/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppData {
  'lastUpdated' : Time,
  'otherPendingAmounts' : Array<OtherPendingAmount>,
  'version' : bigint,
  'ledgerState' : [] | [string],
  'userProfile' : [] | [UserProfile],
}
export type Category = { 'accomodation' : null } |
  { 'cashWithdrawal' : null } |
  { 'other' : null } |
  { 'food' : null } |
  { 'transport' : null } |
  { 'tips' : null } |
  { 'shopping' : null } |
  { 'entryFee' : null } |
  { 'activity' : null };
export interface CoTravellerIncome {
  'tripTime' : [] | [TripTime],
  'date' : Date,
  'note' : [] | [string],
  'amount' : bigint,
}
export interface Date { 'day' : bigint, 'month' : bigint, 'year' : bigint }
export interface Expense {
  'tripTime' : [] | [TripTime],
  'date' : Date,
  'note' : [] | [string],
  'category' : Category,
  'amount' : bigint,
}
export interface OtherPendingAmount {
  'id' : string,
  'date' : Date,
  'traveller' : string,
  'comment' : [] | [string],
  'amount' : bigint,
}
export interface ShareAccessEntry {
  'permissions' : Array<TabPermission>,
  'email' : string,
}
export interface SharedDataResult {
  'permissions' : Array<TabPermission>,
  'ledgerState' : [] | [string],
}
export interface TabPermission { 'access' : string, 'tabKey' : string }
export type Time = bigint;
export type TripTime = { 'morning' : null } |
  { 'evening' : null };
export interface UserProfile { 'name' : string }
export interface UserProfileExtended {
  'sex' : [] | [string],
  'vehicleNumber' : [] | [string],
  'phone' : [] | [string],
  'profilePicture' : [] | [string],
  'lastName' : [] | [string],
  'firstName' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoTravellerIncome' : ActorMethod<[CoTravellerIncome], undefined>,
  'addExpense' : ActorMethod<[Expense], undefined>,
  'addExpenses' : ActorMethod<[Array<Expense>], undefined>,
  'addOrUpdateOtherPendingAmount' : ActorMethod<
    [OtherPendingAmount],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteOtherPendingAmount' : ActorMethod<[string], undefined>,
  'fetchAppData' : ActorMethod<[], [] | [AppData]>,
  'getAdminSharedData' : ActorMethod<[Principal], [] | [SharedDataResult]>,
  'getAllBalances' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserProfileExtended' : ActorMethod<[], [] | [UserProfileExtended]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoTravellerIncomes' : ActorMethod<[Principal], Array<CoTravellerIncome>>,
  'getExpenses' : ActorMethod<[Principal], Array<Expense>>,
  'getOtherPendingAmounts' : ActorMethod<[], Array<OtherPendingAmount>>,
  'getShareAccessConfig' : ActorMethod<[], Array<ShareAccessEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerSharedUserEmail' : ActorMethod<[string], undefined>,
  'saveAppData' : ActorMethod<[AppData], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfileExtended' : ActorMethod<
    [UserProfileExtended],
    undefined
  >,
  'saveShareAccessConfig' : ActorMethod<[Array<ShareAccessEntry>], undefined>,
  'startCharge' : ActorMethod<[string, bigint, Array<Principal>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];