/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShareAccessEntry {
    permissions: Array<TabPermission>;
    email: string;
}
export type Time = bigint;
export interface UserProfileExtended {
    sex?: string;
    vehicleNumber?: string;
    phone?: string;
    profilePicture?: string;
    lastName?: string;
    firstName?: string;
}
export interface OtherPendingAmount {
    id: string;
    date: Date_;
    traveller: string;
    comment?: string;
    amount: bigint;
}
export interface Date_ {
    day: bigint;
    month: bigint;
    year: bigint;
}
export interface AppData {
    lastUpdated: Time;
    otherPendingAmounts: Array<OtherPendingAmount>;
    version: bigint;
    ledgerState?: string;
    userProfile?: UserProfile;
}
export interface Expense {
    tripTime?: TripTime;
    date: Date_;
    note?: string;
    category: Category;
    amount: bigint;
}
export interface SharedDataResult {
    permissions: Array<TabPermission>;
    ledgerState?: string;
}
export interface CoTravellerIncome {
    tripTime?: TripTime;
    date: Date_;
    note?: string;
    amount: bigint;
}
export interface TabPermission {
    access: string;
    tabKey: string;
}
export interface UserProfile {
    name: string;
}
export enum Category {
    accomodation = "accomodation",
    cashWithdrawal = "cashWithdrawal",
    other = "other",
    food = "food",
    transport = "transport",
    tips = "tips",
    shopping = "shopping",
    entryFee = "entryFee",
    activity = "activity"
}
export enum TripTime {
    morning = "morning",
    evening = "evening"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addCoTravellerIncome(income: CoTravellerIncome): Promise<void>;
    addExpense(expense: Expense): Promise<void>;
    addExpenses(expenses: Array<Expense>): Promise<void>;
    addOrUpdateOtherPendingAmount(amount: OtherPendingAmount): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteOtherPendingAmount(id: string): Promise<void>;
    fetchAppData(): Promise<AppData | null>;
    getAdminSharedData(admin: Principal): Promise<SharedDataResult | null>;
    getAdminSharedDataByEmail(admin: Principal, email: string): Promise<SharedDataResult | null>;
    getAllBalances(): Promise<Array<[Principal, bigint]>>;
    getBalance(): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserProfileExtended(): Promise<UserProfileExtended | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoTravellerIncomes(user: Principal): Promise<Array<CoTravellerIncome>>;
    getExpenses(user: Principal): Promise<Array<Expense>>;
    getOtherPendingAmounts(): Promise<Array<OtherPendingAmount>>;
    getShareAccessConfig(): Promise<Array<ShareAccessEntry>>;
    getShareAccessVisitCounts(): Promise<Array<[string, bigint]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordSharedUserVisit(admin: Principal, email: string): Promise<void>;
    registerSharedUserEmail(email: string): Promise<void>;
    saveAppData(newAppData: AppData): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCallerUserProfileExtended(profile: UserProfileExtended): Promise<void>;
    saveShareAccessConfig(configs: Array<ShareAccessEntry>): Promise<void>;
    startCharge(description: string, amount: bigint, participants: Array<Principal>): Promise<void>;
}
import type { AppData as _AppData, Category as _Category, CoTravellerIncome as _CoTravellerIncome, Date as _Date, Expense as _Expense, OtherPendingAmount as _OtherPendingAmount, SharedDataResult as _SharedDataResult, TabPermission as _TabPermission, Time as _Time, TripTime as _TripTime, UserProfile as _UserProfile, UserProfileExtended as _UserProfileExtended, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCoTravellerIncome(arg0: CoTravellerIncome): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoTravellerIncome(to_candid_CoTravellerIncome_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoTravellerIncome(to_candid_CoTravellerIncome_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_Expense_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_Expense_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExpenses(arg0: Array<Expense>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenses(to_candid_vec_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenses(to_candid_vec_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addOrUpdateOtherPendingAmount(arg0: OtherPendingAmount): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateOtherPendingAmount(to_candid_OtherPendingAmount_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateOtherPendingAmount(to_candid_OtherPendingAmount_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteOtherPendingAmount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOtherPendingAmount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOtherPendingAmount(arg0);
            return result;
        }
    }
    async fetchAppData(): Promise<AppData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAppData();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAppData();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminSharedData(arg0: Principal): Promise<SharedDataResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminSharedData(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminSharedData(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminSharedDataByEmail(arg0: Principal, arg1: string): Promise<SharedDataResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminSharedDataByEmail(arg0, arg1);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminSharedDataByEmail(arg0, arg1);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBalances(): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBalances();
            return result;
        }
    }
    async getBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfileExtended(): Promise<UserProfileExtended | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfileExtended();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfileExtended();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoTravellerIncomes(arg0: Principal): Promise<Array<CoTravellerIncome>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoTravellerIncomes(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoTravellerIncomes(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(arg0: Principal): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOtherPendingAmounts(): Promise<Array<OtherPendingAmount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOtherPendingAmounts();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOtherPendingAmounts();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShareAccessConfig(): Promise<Array<ShareAccessEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShareAccessConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShareAccessConfig();
            return result;
        }
    }
    async getShareAccessVisitCounts(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShareAccessVisitCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShareAccessVisitCounts();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordSharedUserVisit(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSharedUserVisit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSharedUserVisit(arg0, arg1);
            return result;
        }
    }
    async registerSharedUserEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSharedUserEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSharedUserEmail(arg0);
            return result;
        }
    }
    async saveAppData(arg0: AppData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAppData(to_candid_AppData_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAppData(to_candid_AppData_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCallerUserProfileExtended(arg0: UserProfileExtended): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfileExtended(to_candid_UserProfileExtended_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfileExtended(to_candid_UserProfileExtended_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveShareAccessConfig(arg0: Array<ShareAccessEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveShareAccessConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveShareAccessConfig(arg0);
            return result;
        }
    }
    async startCharge(arg0: string, arg1: bigint, arg2: Array<Principal>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startCharge(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startCharge(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AppData_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppData): AppData {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_CoTravellerIncome_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoTravellerIncome): CoTravellerIncome {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_OtherPendingAmount_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OtherPendingAmount): OtherPendingAmount {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SharedDataResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SharedDataResult): SharedDataResult {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TripTime_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripTime): TripTime {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileExtended_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileExtended): UserProfileExtended {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppData]): AppData | null {
    return value.length === 0 ? null : from_candid_AppData_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SharedDataResult]): SharedDataResult | null {
    return value.length === 0 ? null : from_candid_SharedDataResult_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileExtended]): UserProfileExtended | null {
    return value.length === 0 ? null : from_candid_UserProfileExtended_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TripTime]): TripTime | null {
    return value.length === 0 ? null : from_candid_TripTime_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastUpdated: _Time;
    otherPendingAmounts: Array<_OtherPendingAmount>;
    version: bigint;
    ledgerState: [] | [string];
    userProfile: [] | [_UserProfile];
}): {
    lastUpdated: Time;
    otherPendingAmounts: Array<OtherPendingAmount>;
    version: bigint;
    ledgerState?: string;
    userProfile?: UserProfile;
} {
    return {
        lastUpdated: value.lastUpdated,
        otherPendingAmounts: from_candid_vec_n17(_uploadFile, _downloadFile, value.otherPendingAmounts),
        version: value.version,
        ledgerState: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.ledgerState)),
        userProfile: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.userProfile))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: _Date;
    traveller: string;
    comment: [] | [string];
    amount: bigint;
}): {
    id: string;
    date: Date_;
    traveller: string;
    comment?: string;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        traveller: value.traveller,
        comment: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.comment)),
        amount: value.amount
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permissions: Array<_TabPermission>;
    ledgerState: [] | [string];
}): {
    permissions: Array<TabPermission>;
    ledgerState?: string;
} {
    return {
        permissions: value.permissions,
        ledgerState: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.ledgerState))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sex: [] | [string];
    vehicleNumber: [] | [string];
    phone: [] | [string];
    profilePicture: [] | [string];
    lastName: [] | [string];
    firstName: [] | [string];
}): {
    sex?: string;
    vehicleNumber?: string;
    phone?: string;
    profilePicture?: string;
    lastName?: string;
    firstName?: string;
} {
    return {
        sex: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.sex)),
        vehicleNumber: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.vehicleNumber)),
        phone: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.phone)),
        profilePicture: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.profilePicture)),
        lastName: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.lastName)),
        firstName: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.firstName))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tripTime: [] | [_TripTime];
    date: _Date;
    note: [] | [string];
    amount: bigint;
}): {
    tripTime?: TripTime;
    date: Date_;
    note?: string;
    amount: bigint;
} {
    return {
        tripTime: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.tripTime)),
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.note)),
        amount: value.amount
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tripTime: [] | [_TripTime];
    date: _Date;
    note: [] | [string];
    category: _Category;
    amount: bigint;
}): {
    tripTime?: TripTime;
    date: Date_;
    note?: string;
    category: Category;
    amount: bigint;
} {
    return {
        tripTime: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.tripTime)),
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.note)),
        category: from_candid_Category_n39(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    morning: null;
} | {
    evening: null;
}): TripTime {
    return "morning" in value ? TripTime.morning : "evening" in value ? TripTime.evening : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accomodation: null;
} | {
    cashWithdrawal: null;
} | {
    other: null;
} | {
    food: null;
} | {
    transport: null;
} | {
    tips: null;
} | {
    shopping: null;
} | {
    entryFee: null;
} | {
    activity: null;
}): Category {
    return "accomodation" in value ? Category.accomodation : "cashWithdrawal" in value ? Category.cashWithdrawal : "other" in value ? Category.other : "food" in value ? Category.food : "transport" in value ? Category.transport : "tips" in value ? Category.tips : "shopping" in value ? Category.shopping : "entryFee" in value ? Category.entryFee : "activity" in value ? Category.activity : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OtherPendingAmount>): Array<OtherPendingAmount> {
    return value.map((x)=>from_candid_OtherPendingAmount_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoTravellerIncome>): Array<CoTravellerIncome> {
    return value.map((x)=>from_candid_CoTravellerIncome_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n37(_uploadFile, _downloadFile, x));
}
function to_candid_AppData_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppData): _AppData {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CoTravellerIncome_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoTravellerIncome): _CoTravellerIncome {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Expense_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expense): _Expense {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_OtherPendingAmount_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OtherPendingAmount): _OtherPendingAmount {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TripTime_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripTime): _TripTime {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileExtended_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileExtended): _UserProfileExtended {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: Date_;
    traveller: string;
    comment?: string;
    amount: bigint;
}): {
    id: string;
    date: _Date;
    traveller: string;
    comment: [] | [string];
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        traveller: value.traveller,
        comment: value.comment ? candid_some(value.comment) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tripTime?: TripTime;
    date: Date_;
    note?: string;
    amount: bigint;
}): {
    tripTime: [] | [_TripTime];
    date: _Date;
    note: [] | [string];
    amount: bigint;
} {
    return {
        tripTime: value.tripTime ? candid_some(to_candid_TripTime_n3(_uploadFile, _downloadFile, value.tripTime)) : candid_none(),
        date: value.date,
        note: value.note ? candid_some(value.note) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastUpdated: Time;
    otherPendingAmounts: Array<OtherPendingAmount>;
    version: bigint;
    ledgerState?: string;
    userProfile?: UserProfile;
}): {
    lastUpdated: _Time;
    otherPendingAmounts: Array<_OtherPendingAmount>;
    version: bigint;
    ledgerState: [] | [string];
    userProfile: [] | [_UserProfile];
} {
    return {
        lastUpdated: value.lastUpdated,
        otherPendingAmounts: to_candid_vec_n43(_uploadFile, _downloadFile, value.otherPendingAmounts),
        version: value.version,
        ledgerState: value.ledgerState ? candid_some(value.ledgerState) : candid_none(),
        userProfile: value.userProfile ? candid_some(value.userProfile) : candid_none()
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sex?: string;
    vehicleNumber?: string;
    phone?: string;
    profilePicture?: string;
    lastName?: string;
    firstName?: string;
}): {
    sex: [] | [string];
    vehicleNumber: [] | [string];
    phone: [] | [string];
    profilePicture: [] | [string];
    lastName: [] | [string];
    firstName: [] | [string];
} {
    return {
        sex: value.sex ? candid_some(value.sex) : candid_none(),
        vehicleNumber: value.vehicleNumber ? candid_some(value.vehicleNumber) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        profilePicture: value.profilePicture ? candid_some(value.profilePicture) : candid_none(),
        lastName: value.lastName ? candid_some(value.lastName) : candid_none(),
        firstName: value.firstName ? candid_some(value.firstName) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tripTime?: TripTime;
    date: Date_;
    note?: string;
    category: Category;
    amount: bigint;
}): {
    tripTime: [] | [_TripTime];
    date: _Date;
    note: [] | [string];
    category: _Category;
    amount: bigint;
} {
    return {
        tripTime: value.tripTime ? candid_some(to_candid_TripTime_n3(_uploadFile, _downloadFile, value.tripTime)) : candid_none(),
        date: value.date,
        note: value.note ? candid_some(value.note) : candid_none(),
        category: to_candid_Category_n7(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripTime): {
    morning: null;
} | {
    evening: null;
} {
    return value == TripTime.morning ? {
        morning: null
    } : value == TripTime.evening ? {
        evening: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    accomodation: null;
} | {
    cashWithdrawal: null;
} | {
    other: null;
} | {
    food: null;
} | {
    transport: null;
} | {
    tips: null;
} | {
    shopping: null;
} | {
    entryFee: null;
} | {
    activity: null;
} {
    return value == Category.accomodation ? {
        accomodation: null
    } : value == Category.cashWithdrawal ? {
        cashWithdrawal: null
    } : value == Category.other ? {
        other: null
    } : value == Category.food ? {
        food: null
    } : value == Category.transport ? {
        transport: null
    } : value == Category.tips ? {
        tips: null
    } : value == Category.shopping ? {
        shopping: null
    } : value == Category.entryFee ? {
        entryFee: null
    } : value == Category.activity ? {
        activity: null
    } : value;
}
function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OtherPendingAmount>): Array<_OtherPendingAmount> {
    return value.map((x)=>to_candid_OtherPendingAmount_n10(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Expense>): Array<_Expense> {
    return value.map((x)=>to_candid_Expense_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
